Basic HTTPServer
soukyomi/kastle pull request #2
Opened 2021-06-12 14:37 UTC by NiumXp

This pull request adds a basic HTTPServer.

Main changes
---
Classes `Connection`, `ServerResponse`, `Request` and subclasses of `ServerError`.

| Class | Description
|-|-|
|Request|Used to read HTTP request messages
|Connection|Used to maintain a raw connection
|ServerResponse|Used to build HTTP response messages

2021-06-12 23:25 UTC, soukyomi requested changes
Some PEP-8 issues and need to make the variable name clearer.

2021-06-12 23:25 UTC, soukyomi commented on kastle/connection.py
> +                 w: asyncio.StreamWriter) -> None:
```suggestion
def __init__(
    self,
    s,
    r: asyncio.StreamReader,
    w: asyncio.StreamWriter
) -> None:
```
To follow PEP-8.

2021-06-12 23:25 UTC, soukyomi commented on kastle/connection.py
> +            verb, target, version = firstline.split(b' ')
```suggestion
            method, target, version = firstline.split(b' ')
```
Since this is a HTTP method.

2021-06-12 23:25 UTC, soukyomi commented on kastle/server.py
> +    def __init__(self, status: HTTPStatus, data: Optional[bytes]=None) -> None:
```suggestion
    def __init__(self, status: HTTPStatus, data: Optional[bytes] = None) -> None:
```
To follow PEP-8.

2021-06-13 00:17 UTC, NiumXp commented on kastle/connection.py
> +                 w: asyncio.StreamWriter) -> None:
The indentation of parameters follows the PEP-8, can you write more examples?

2021-06-13 01:08 UTC, soukyomi requested changes

2021-06-13 01:08 UTC, soukyomi commented on kastle/connection.py
> +CRLN = b"\r\n"
```suggestion
CRLF = b"\r\n"
```
The correct term is *Carriage Return and Line Feed*.

2021-06-13 01:08 UTC, soukyomi commented on kastle/connection.py
> +CRLN = b"\r\n"
```suggestion
from . import errors


CRLN = b"\r\n"
```
Please, add one more blank-line to follow PEP-8 conventions.

2021-06-13 15:36 UTC, NiumXp commented on kastle/connection.py
> +CRLN = b"\r\n"
This follow the PEP-8. The two blank lines is for functions and classes.

2021-06-13 15:41 UTC, soukyomi commented
LGTM, thank you.

2021-06-13 15:42 UTC, soukyomi approved these changes

2021-06-13 15:43 UTC, soukyomi commented
LGTM, thank you.

2021-06-13 15:43 UTC, merged